CREATE USER weather_app WITH PASSWORD 'weather_app_password';

GRANT CONNECT ON DATABASE postgres TO weather_app;
GRANT USAGE, CREATE ON SCHEMA public TO weather_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO weather_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO weather_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO weather_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO weather_app;
